<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="utf-8" %>
<html>
<head>
    <title>plan</title>
</head>
<body>
<table>
    <tr>
        <td>plan_id</td>
        <td>user_id</td>
        <td>plan_content</td>
        <td>plan_date</td>
    </tr>
    <tr>
        <td>${plan.plan_id}</td>
        <td>${plan.plan_id}</td>
        <td>${plan.plan_content}</td>
        <td>${plan.plan_date}</td>
    </tr>
</table>
</body>
</html>