<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="utf-8" %>
<html>
<head>
    <title>time</title>
</head>
<body>
<table>
    <tr>
        <td>arrange_id</td>
        <td>user_id</td>
        <td>arrange_content</td>
        <td>arrange_place</td>
        <td>arrange_time</td>
        <td>arrange_if_prompt</td>
        <td>arrange_if_prompt_time</td>
    </tr>
    <tr>
        <td>${arrangement.arrange_id}</td>
        <td>${arrangement.user_id}</td>
        <td>${arrangement.arrange_content}</td>
        <td>${arrangement.arrange_place}</td>
        <td>${arrangement.arrange_time}</td>
        <td>${arrangement.arrange_if_prompt}</td>
        <td>${arrangement.arrange_if_prompt_time}</td>
    </tr>
</table>
</body>
</html>